import { StyleSheet } from "react-native"

export const getStyles = (currentColors: any) =>
    StyleSheet.create({
        container: {
            flex: 1,
            backgroundColor: currentColors.background,
        },
        header: {
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
            paddingHorizontal: 15,
            paddingVertical: 15,
            backgroundColor: currentColors.headerBackground,
            position: "relative" as any, // "sticky" not fully supported in RN without external layout or careful scroll view handling, keeping relative for now or specific platform checks.
            top: 0,
            zIndex: 10000,
            width: "100%",
            elevation: 3,
            shadowColor: "#000",
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.1,
            shadowRadius: 3,
        },
        headerLeft: {
            flexDirection: "row",
            alignItems: "center",
            gap: 10,
        },
        headerTitle: {
            color: currentColors.headerText,
            fontSize: 18,
            fontWeight: "600",
        },
        backButton: {
            padding: 5,
        },
        heartButton: {
            padding: 8,
        },
        searchContainer: {
            flexDirection: "row",
            paddingHorizontal: 15,
            paddingVertical: 12,
            gap: 10,
            backgroundColor: currentColors.filterBackground,
            borderBottomWidth: 1,
            borderBottomColor: currentColors.dropdownBorder,
            alignItems: "center",
            marginBottom: 10,
        },
        searchTypeContainer: {
            width: 110,
            height: 42,
            backgroundColor: currentColors.dropdownBackground,
            borderRadius: 8,
            borderWidth: 1,
            borderColor: currentColors.dropdownBorder,
            justifyContent: "center",
            overflow: "hidden",
        },
        searchInputContainer: {
            flex: 1,
            flexDirection: "row",
            alignItems: "center",
            backgroundColor: currentColors.dropdownBackground,
            borderRadius: 8,
            paddingHorizontal: 12,
            borderWidth: 1,
            borderColor: currentColors.dropdownBorder,
            height: 42,
        },
        searchInput: {
            flex: 1,
            paddingVertical: 10,
            marginLeft: 8,
            fontSize: 14,
            color: currentColors.AppointmentColor,
        },
        clearButton: {
            padding: 4,
        },
        section: {
            padding: 16,
            backgroundColor: currentColors.cardBackground || currentColors.background,
            borderRadius: 12,
            marginHorizontal: 12,
            marginBottom: 20,
            shadowColor: "#000",
            shadowOffset: { width: 0, height: 1 },
            shadowOpacity: 0.05,
            shadowRadius: 2,
            elevation: 2,
            borderWidth: 1,
            borderColor: currentColors.dropdownBorder,
        },
        sectionTitle: {
            fontSize: 18,
            fontWeight: "600",
            marginBottom: 16,
            color: currentColors.AppointmentColor,
        },
        label: {
            fontSize: 14,
            marginBottom: 8,
            color: currentColors.AppointmentColor,
            fontWeight: "500",
        },
        input: {
            borderWidth: 1,
            borderColor: currentColors.dropdownBorder,
            borderRadius: 8,
            padding: 12,
            marginBottom: 16,
            backgroundColor: currentColors.dropdownBackground,
            color: currentColors.AppointmentColor,
            fontSize: 15,
        },
        readOnlyInput: {
            backgroundColor: currentColors.dropdownBorder + "40",
        },
        radioGroup: {
            marginBottom: 16,
        },
        radioButtonRow: {
            flexDirection: "row",
            flexWrap: "wrap",
        },
        radioButton: {
            flexDirection: "row",
            alignItems: "center",
            marginRight: 16,
        },
        radioLabel: {
            fontSize: 14,
            color: currentColors.AppointmentColor,
        },
        pickerContainer: {
            borderWidth: 1,
            borderColor: currentColors.dropdownBorder,
            borderRadius: 8,
            marginBottom: 16,
            backgroundColor: currentColors.dropdownBackground,
            overflow: "hidden",
        },
        picker: {
            height: 50,
            color: currentColors.AppointmentColor,
        },
        datePickerButton: {
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
            paddingVertical: 4,
        },
        dateText: {
            color: currentColors.AppointmentColor,
            fontSize: 15,
        },
        buttonContainer: {
            flexDirection: "row",
            justifyContent: "space-between",
            marginTop: 24,
            gap: 12,
        },
        primaryButton: {
            backgroundColor: currentColors.activeTabBackground,
            padding: 14,
            borderRadius: 8,
            alignItems: "center",
            flex: 1,
            elevation: 2,
            shadowColor: "#000",
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.2,
            shadowRadius: 3,
        },
        updateButton: {
            backgroundColor: currentColors.updateButtonBackground || "#007AFF",
            padding: 14,
            borderRadius: 8,
            alignItems: "center",
            flex: 1,
            elevation: 2,
            shadowColor: "#000",
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.2,
            shadowRadius: 3,
        },
        secondaryButton: {
            backgroundColor: currentColors.secondaryButtonBackground || "#FF3B30",
            padding: 14,
            borderRadius: 8,
            alignItems: "center",
            flex: 1,
            elevation: 1,
            shadowColor: "#000",
            shadowOffset: { width: 0, height: 1 },
            shadowOpacity: 0.1,
            shadowRadius: 2,
        },
        buttonText: {
            color: currentColors.activeTabText,
            fontSize: 16,
            fontWeight: "600",
        },
        secondaryButtonText: {
            color: currentColors.secondaryButtonText || "#FFFFFF",
            fontSize: 16,
            fontWeight: "600",
        },
        selectedServicesContainer: {
            marginTop: 8,
            marginBottom: 16,
            padding: 12,
            backgroundColor: currentColors.dropdownBackground,
            borderRadius: 8,
            borderWidth: 1,
            borderColor: currentColors.dropdownBorder,
        },
        selectedServicesTitle: {
            fontSize: 14,
            fontWeight: "600",
            marginBottom: 12,
            color: currentColors.AppointmentColor,
        },
        chipContainer: {
            flexDirection: "row",
            flexWrap: "wrap",
            gap: 8,
            marginTop: 8,
        },
        chip: {
            flexDirection: "row",
            alignItems: "center",
            backgroundColor: currentColors.cardBackground || currentColors.background,
            paddingVertical: 6,
            paddingHorizontal: 10,
            borderRadius: 16,
            borderWidth: 1,
            borderColor: currentColors.dropdownBorder,
        },
        chipText: {
            fontSize: 13,
            color: currentColors.dropdownText,
            marginRight: 6,
            maxWidth: 150,
        },
        chipRemoveButton: {
            padding: 2,
        },
        searchPicker: {
            width: 120,
            color: currentColors.AppointmentColor,
        },
        requiredStar: {
            color: "#FF3B30",
            marginLeft: 2,
        },
        errorText: {
            color: "#FF3B30",
            fontSize: 12,
            marginTop: -12,
            marginBottom: 12,
        },
        connectionStatusBar: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "center",
            padding: 8,
            margin: 10,
            borderRadius: 6,
            backgroundColor: "#FF3B30",
        },
        connectionStatusText: {
            color: "white",
            fontSize: 13,
            fontWeight: "500",
            marginLeft: 6,
        },
        stepIndicator: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "center",
            marginVertical: 20,
            paddingHorizontal: 40,
        },
        step: {
            width: 32,
            height: 32,
            borderRadius: 16,
            backgroundColor: currentColors.dropdownBackground,
            borderWidth: 2,
            borderColor: currentColors.dropdownBorder,
            justifyContent: "center",
            alignItems: "center",
            zIndex: 2,
        },
        activeStep: {
            backgroundColor: currentColors.activeTabBackground,
            borderColor: currentColors.activeTabBackground,
        },
        stepText: {
            color: currentColors.AppointmentColor,
            fontWeight: "600",
        },
        activeStepText: {
            color: currentColors.activeTabText,
        },
        stepLine: {
            flex: 1,
            height: 2,
            backgroundColor: currentColors.dropdownBorder,
            marginHorizontal: -2,
            zIndex: 1,
        },
        lockedText: {
            color: currentColors.AppointmentColor,
            fontSize: 12,
            marginTop: -12,
            marginBottom: 12,
            fontStyle: 'italic',
            opacity: 0.7,
        },
        loadingContainer: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            padding: 15,
        },
        loadingText: {
            marginLeft: 10,
            color: currentColors.AppointmentColor,
            fontSize: 14,
        },
        feeContainer: {
            flexDirection: "row",
            justifyContent: "space-between",
            gap: 12,
            marginBottom: 16,
        },
        feeItem: {
            flex: 1,
        },
    });
